# Tutorials

To complete these tutorials, copy and paste the code into the Google Earth Engine (GEE) Code Editor and save the file to your GEOG567 repository. As you move through the script closely read the comments (denoted by //), which will give you information and prompt you to make changes to the script

## Tutorial 1: Introduction to Javascript

After completing this tutorial you should be able to:

- Create and assign variables in JavaScript
- Use strings, numbers, lists, and objects
- Print variables and objects to the Google Earth Engine console
- Write and interpret comments in Javascript code

``` javascript
//Welcome to the Google Earth Engine Code Editor!
//In this course, we will be coding in JavaScript
//This exercise will introduce you to the basics of
//scripting in the GEE environment. 

//Any line with "//" before it is a comment, which means
//that those lines with not "run".

//Comments are used to keep track of what different commands
//are doing. You should include a descriptive comment
//above each line of code

//It is good luck to print "Hello, World" whenever you are
//learning a new programming language. Fill in the 
//print command below and click "Run" using the button at the top of the script
// Notice that this code executes into the "console" on the right. 

// A ; should be placed after each line of code. GEE will
//allow code to run without it, but it is best practice.

print("");


//Now we are really ready to get started.


//The first important thing to learn is how to create a 
//variable. In JavaScript you must "declare" variables 
//using the following syntax

//var BLANK =    ;


//Variables can be made up of all sorts of things, but 
//the simplest variables are usually "string" or "numeric" 
//variables. 

//Text strings must be contained within quotations

// var BLANK = "TEXT";


//Below, create the string "North Carolina" and assign it 
// to a variable named "state"


//Now click run. You will notice that nothing is printed
//to your console for the "state" variable. Uncomment
// the command below and re-run the script

//print(state);


//Without the print command, the "state" variable is still
//created, but there is not any output. Print commands
//are used often to check progress on code or to explore
//images and image collections (which we will learn about later)


//numeric variables should not be contained in quotes

//create a numeric variable called "state_population" and 
//assign the value 10439388 (2020 census population of NC)


//print the "state_population" variable


//sometimes you want to include multiple values in a 
//single variable. This is called a list and it looks like 

// var list = [VALUE, VALUE, VALUE, VALUE];

//create a list called "cities" that holds the values Raleigh,
//Charlotte, Asheville, and Wilmington. Remember that 
// strings need to be in quotes. Print the "cities" list


//Objects allow you to hold multiple values in a "key"- "value"
//pair and look like 

//uncomment the lines of code below by pressing "command" and "slash"

// var raleigh_data = {
//            "city" : "Raleigh",
//            "coordinates" : [-78.644257, 35.787743],
//            "population" : 476587} ; 


//you can access the whole object by
//print(raleigh_data);

//you can also access a single part of an object like
//print(raleigh_data.population);
                      

//create your own sample object below


//now print a part of the object here
```

## Tutorial 2: Introduction to GEE API

After completing this tutorial you should be able to:

- Explain the difference between client-side and server-side processing in Google Earth Engine
- Use basic Google Earth Engine API (ee) functions for mathematical and logical operations
- Create, manipulate, and analyze server-side lists using the GEE API
- Apply reducers and filters to perform basic data processing in Google Earth Engine

``` javascript
// Google Earth Engine's code editor allows us to access the 
//Earth Engine API. The Earth Engine API is very powerful and 
//contains methods to do most everything we would want to do in 
//terms of image processing and analysis

//Click on the "Docs" tab to the right. This documents all of the 
//available functions in the Earth Egnine API. 

//the API functions have the prefix ee (for Earth Engine)

//API functions are "server-side" meaning that the processing
//will take place on Google's servers, as opposed to your
//local computer (client-side).

//Much of the power of Earth Engine is the ability to use Google's servers
//for processing. Therefore, we should be using "server-side" 
//functions as much as possible. 


//Let's look at a simple example. We can do basic arithmetic 
//on the server-side or the client side. 

//The client side looks like this
var client = 2 + 2;
print(client);

//The server side uses an API function and looks like this
var server = ee.Number(2).add(2);
print(client);

//The client side looks a little simpler, and in this example, they
//work at a similar speed. But for advanced processing, server-side
//functions are the only way to achieve something. It is best
//practice to get used to using server-side functions. 

// Now, let's explore more common server-side functions.

// Math Operations
// We can perform many other math operations using server-side functions

var num1 = ee.Number(10);
var num2 = ee.Number(5);

var addition = num1.add(num2);
var subtraction = num1.subtract(num2);
var multiplication = num1.multiply(num2);
var division = num1.divide(num2);

print(addition);
print(subtraction);
print(multiplication);
print(division);

// Logical Operations
// We can also perform logical operations

var isEqual = num1.eq(num2);
var isGreater = num1.gt(num2);
var isLess = num1.lt(num2);

print(isEqual);
print(isGreater);
print(isLess);

// Lists
// we can create lists on the server-side by adding the ee. 
//before the list function

var numbers = ee.List([1, 2, 3, 4, 5]);
print(numbers);

// Reduce a list
// Let's find the sum of the numbers in the list
var sum = numbers.reduce(ee.Reducer.sum());
print(sum);

//Sort a list in ascending and descending order.
var unsortedList = ee.List([10, 2, 30, 5, 7]);
var sortedListAsc = unsortedList.sort();
print(sortedListAsc);


// Filter elements in a list based on a condition.
var filteredList = unsortedList.filter(ee.Filter.gt('item', 5));
print(filteredList);

// Count the number of elements in a list.
var countElements = unsortedList.size();
print("Number of elements:", countElements);


//Server-side function practice
// First, create a list of 10 numbers

//1. Write a command to find and print the maximum value in the list


//2. Write a command to sum the numbers in the list


//3. Write a command to filter the list to only numbers under a certain
//value

//4. Write a command to count how many elements are in the 
//filtered list. 


//Scripting for GEE uses JavaScript, but you do not need to be
//an expert in JavaScript to use it. Instead, we use JavaScript
//largely to access the API, where we are using server-side 
//functions to accomplish what we want to.
```

## Tutorial 3: Introduction to Images and Image Collections

After completing this tutorial you should be able to:

- Distinguish between an ee.Image() and an ee.ImageCollection()
- Load and inspect images and image collections in GEE
- Access image metadata

``` javascript
// An ee.Image is a single satellite image or other raster dataset.
// An ee.ImageCollection is a collection of ee.Images.
// It often represents all images from a particular satellite or dataset,
// which can then be filtered by location, date, or other properties.

//Here is your first image!!!
//when you run this code, it will load the image, but we won't see anything
var firstImage = ee.Image('LANDSAT/LC09/C02/T1_L2/LC09_016035_20260510');


//to get information about the image, use the print command
//print(firstImage);

//by printing, you can get information about the bands available in the
//image, as well as the image properties

//how many bands are in the image? 

//what is the cloud cover of the image? 

//when was the image taken? (this is a hard one)

//can you figure out an EASIER way to figure out the date of the image? 
//hint, look at the name of the image


//That image came from an Image Collection of all LANDSAT9 images. 
//visit the link below to see the Image Collection in the data catalog, which
//can give you a bunch of information about the collection before
//even adding it to GEE

//https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LC09_C02_T1_L2

//note that the collection name is just the first part of our firstImage
var firstCollection = ee.ImageCollection('LANDSAT/LC09/C02/T1_L2')


//try printing our collection, what happens? 


//we can't print image collections that are too large. Let's start by
//looking at a smaller set of images. You'll learn a lot more about filtering later
//so don't worry now

var filteredCollection = firstCollection.filterDate('2025-08-01', '2025-08-05');

// how many images are in our filtered collection?


//what is the image name of the 28th feature in the collection? 


//how much cloud coverage is there in the 124 feature in the collection? 
```

## Tutorial 4: Visualizing Single Bands

After completing this tutorial you should be able to:

- Display single-band images in Google Earth Engine
- Apply visualization parameters such as minimum and maximum values
- Use the Inspector tool to explore pixel values in an image
- Create and apply color palettes to improve single-band image visualization

``` javascript

//Creating appropriate visualizations in Google Earth Engine
//is one of the most important skills that we can learn. 

//There are different visualization practices for single vs. multi-band
//images. Today, we are going to focus on single-band images. 

var image = ee.Image('CGIAR/SRTM90_V4');

//to add an image to the map, we use the following command
Map.addLayer(image);


//You're probably staring at a gray screen. That's not very helpful,
//is it. 

//let's add a minimum and maximum value
Map.addLayer(image, {min: 0, max:250});


//can you figure out what this data might be showing? 
//visit the data catalog to get some more information
//https://www.google.com/search?q=CGIAR%2FSRTM90_V4&oq=CGIAR%2FSRTM90_V4&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIKCAEQABiABBiiBDIHCAIQABjvBTIHCAMQABjvBTIKCAQQABiiBBiJBTIHCAUQABjvBTIGCAYQRRg60gEHMTg3ajBqN6gCALACAA&sourceid=chrome&source=chrome.ob&ie=UTF-8


//Open up the Layers tab. There should be two images in there. Click the first
//image off. That was the first image we added without any visualization parameters


//Using the selection bar next to the second image, lower the opacity to see
//the basemap


//Zoom out to the whole US. This visualization looks okay, but
//not great, especially if you zoom into an area like Chapel Hill.

//Use the Inspector tab to click around Chapel Hill and see the pixel values

//Modify the min and max to make sense for Chapel Hill. 

//Greyscale is ok, but we might want to use some colors to 
//better distinguish patterns. 

//Palettes let you add color to single-band images.
//Here is an example of how to use a palette
//Map.addLayer(image, {min: 0, max: 3000, palette: ['blue', 'green', 'red']});

//add a palette to the command you wrote above for Chapel Hill. 

//Colors can be referenced by name, or by HEX code. Visit this
//site for information on colors 
//https://en.wikipedia.org/wiki/Web_colors


//Create a new 4 color palette and re-visualize your data with it
```

## Tutorial 5: Visualizing a Multi-Band Image

After completing this tutorial you should be able to:

- Visualize multi-band images in Google Earth Engine
- Create true-color and false-color composites using different band combinations
- Apply appropriate minimum and maximum values for multi-band visualizations

``` javascript

//Visualizing a multi-band image requires a couple more steps than a single band image

//The image below is a Landsat 8 image.
var image = ee.Image("LANDSAT/LC08/C02/T1_L2/LC08_016035_20240325");


//How many bands are there in this image?

//To visualize a multiband image, the first thing you need to 
// do is decide what bands to visualize. 


//Uncomment the line below. This will visualize the image in a
//"true color" composite
//Map.addLayer( image, { bands: ['SR_B4', 'SR_B3', 'SR_B2']}  )


//You will notice that the image is very dark. We need to set
//appropriate min and max values. 
//Here is a code snippet that I use to help me pick min/max vlaues
//It samples 1000 pixels in the dataset
//and finds the 2nd and 98th percentile, which I use for the min and max
//You can any of the bands. 


// var stats = image.select('SR_B4')
//   .sample({
//     region: image.geometry(),
//     numPixels: 1000,
//     scale: 30
//   })
//   .reduceColumns({
//     reducer: ee.Reducer.percentile([2, 98]),
//     selectors: ['SR_B4']
//   });

// print(stats);

//using the values from the command above, modify the visualization
//script by adding a min and max


//the bands selected will automatically map to the Red, Green, and Blue
//values for the pixel. 

//select three other bands from the dataset (by printing metadata)
//change your visualization to use those three bands. 
//What does the image look like? 
```

## Tutorial 6: Filtering Image Collections

After completing this tutorial you should be able to:

- Create and use geometries to define areas of interest
- Filter image collections by date, location, and metadata properties.
- Create and use geometries to define areas of interest

``` javascript
//A major pre-processing task that we need to do for image collections 
//is filter based on time, location, or metadata properties

//let's start with the Landsat9 image collection
var dataset = ee.ImageCollection('LANDSAT/LC09/C02/T1_L2');

//we can filter by a date or set of dates using the following command
var filter1 = ee.ImageCollection('LANDSAT/LC09/C02/T1_L2').filterDate('2026-01-01', '2026-01-10');
//print the image collection. How many images are there? 


//we can filter by a location two different ways. 
//we can define a lat/lon
var chapelHill = ee.Geometry.Point([-79.039, 35.9262]);

var filter2 = dataset.filterBounds(chapelHill);
//How many images are there? 

//we can also add geometry to filter by using the map interface
//click the point button at the top left of the map and add a point 
//in Greenville, NC

//see that it adds the geometry to the top tab of our script. 
//This is our "Import" area, which we'll use more in the future

//change the name from geometry to greenville and filter the image collection
//to images that cover greenville. 
//How many images are there? 


//finally, we can filter by metadata properties. A super common
//filter is to filter to low cloud images
var filter4 = dataset.filter(
    ee.Filter.lt('CLOUD_COVER', 10)
);


//we can also stack filters

var stackedFilter = ee.ImageCollection('LANDSAT/LC09/C02/T1_L2')
                      .filterBounds(chapelHill)
                      .filter(ee.Filter.lt('CLOUD_COVER', 10));
                      

//how many images cover greenville and have a cloud cover of less than 5%?
```

## Tutorial 7: Quality Masks and Image Preprocessing

```javascript
//Satellite images often contain clouds, cloud shadows,or other poor-quality pixels.
//Most satellite datasets include one or more Quality Assurance (QA) bands that indicate the quality of each pixel.


//Here is an image of Chapel Hill
var image = ee.Image('LANDSAT/LC08/C02/T1_L2/LC08_016035_20230627');

//add a true-color visualization of the image to the map. 
//Do you notice the cloud cover?


//QA bands store information about each pixel using binary flags.
//Each binary digit is called a bit. A bit can either be 0 (false) or 1 (true).

//For the Landsat QA_PIXEL band:
//
//Bit 0 = Fill (valid pixel is 0)
//Bit 1 = Dilated Cloud
//Bit 2 = Cirrus
//Bit 3 = Cloud
//Bit 4 = Cloud Shadow


//If we wanted to determine whether a pixel contains a cloud, we would create
//a binary number with only Bit 3 turned on. 

var dialatedBit = 1 << 1;
var cirrusBit = 1 << 2;
var cloudBit = 1 << 3;
var shadowBit = 1 << 4;


//bitwiseAnd() compares this binary number to the QA band.
//If Bit 3 is turned on in the QA band, the result will be nonzero.

var cloud = qa.bitwiseAnd(cloudBit).eq(0);

//Display the cloud mask.

//Create masks for the remaining quality flags

//We can stack masks by using the following 
// var clearImage = cloud.and(SECONDCONDITION).and(THIRDCONDITION)...

//Write a command that stacks all the masks. 


//We can then apply that to the original image
//var masked = image.updateMask(clear);


//Display the masked image.


//This worked for one image. However, image collections hundreds or thousands
//of images. Rather than repeating this code for every image, we can write a function


var maskClouds = function(image){
  var qa = image.select('QA_PIXEL');
  var dilatedCloud = qa.bitwiseAnd(1 << 1).eq(0);
  var cirrus = qa.bitwiseAnd(1 << 2).eq(0);
  var cloud = qa.bitwiseAnd(1 << 3).eq(0);
  var shadow = qa.bitwiseAnd(1 << 4).eq(0);
  var snow = qa.bitwiseAnd(1 << 5).eq(0);
  var clear =
       dilatedCloud
      .and(cirrus)
      .and(cloud)
      .and(shadow)
      .and(snow);

  return image.updateMask(clear);
};


//Load a Landsat image collection over Chapel Hill.

var collection = ee.ImageCollection("LANDSAT/LC09/C02/T1_L2")
    .filterBounds(ee.Geometry.Point(-79.0558, 35.9132))
    .filterDate('2025-05-01', '2025-09-30');


//Apply the masking function to every image
//in the collection.

var cleanCollection = collection.map(maskClouds);

```

## Tutorial 8: Image Composites

After completing this tutorial you should be able to:

- Explain the difference between mosaicking and compositing
- Create mosaics
- Generate composite images using aggregation functions

``` javascript
//Compositing involves selecting an aggregation function to 
//turn an image collection into a single summary image. 

//Reload your cloud masked collection from Tutorial 7. 

//How many images are there? 


//What if you wanted to produce one image to summarize all of the
//images in the image collection? 


//We can create a composite image by applying an aggregation function 
//to the image collection.

var compositeLandsat = cleanCollection.median(); 


//Visualize the composite

//other options include median(), min(), max(), etc.


//Make a composite using a different aggregation option. Can you notice any
//differences?
```

## Tutorial 9: False Color Visualizations

After completing this tutorial you should be able to:

- Explain the difference between natural-color and false-color image visualizations
- Create false-color composites using different band combinations
- Interpret how false-color imagery reveals features not visible in natural-color images

``` javascript
//so far, we have only worked with "Natural Color" visualizations, which means that we 
//map the RGB for the image to the Red, Green, and Blue bands on the satellite.

//For instance, here is a Sentinel-2 Image of Chapel Hill
var image = ee.Image('COPERNICUS/S2_SR_HARMONIZED/20260313T160041_20260313T160757_T17SPV')

//natural color visualization
Map.addLayer(
    image, 
    {
        bands: ['B4', 'B3', 'B2'], 
        min: 160,
        max: 2200
    },
    'Sentinel-2 Image of CH' 
);

//However, there are actually many more bands in the image. We can assign bands other
//than RGB to the RBG values of the visualization. This is called a False-Color Visualization

//There are many different sets of combinations of bands that are designed to help us visualize
//different things. 


//For instance, using the near infrared band ,red, and green band can assess plant density 
Map.addLayer(
    image, 
    {
        bands: ['B8', 'B4', 'B3'], 
        min: 160,
        max: 2200
    },
    'Vegetation' 
);

//What can you learn about the CH area from this visualization that you can't
//see in the natural color? 

//Using the SWIR-1, near infrared, and blue bands can assess agricultural health 
Map.addLayer(
    image, 
    {
        bands: ['B11', 'B8', 'B2'], 
        min: 160,
        max: 2200
    },
    'Agriculture' 
);

//What can you learn about the CH area from this visualization that you can't
//see in the natural color? 

//Using the SWIR-1,SWIR-2, and blue bands can find geological features
Map.addLayer(
    image, 
    {
        bands: ['B12', 'B11', 'B2'], 
        min: 160,
        max: 2200
    },
    'Geology' 
);

//What can you learn about the CH area from this visualization that you can't
//see in the natural color? 
```

## Tutorial 10: Spectral Indices, Thresholding, and Masking

After completing this tutorial you should be able to:

- Calculate spectral indices using band math and .normalizedDifference()
- Apply thresholds to create binary classifications
- Reclassify continuous index values into multiple categories
- Use masks to isolate selected conditions in images

``` javascript
//In the last tutorial, we learned how to create false-color composites
//using different Sentinel-2 bands to visualize features around Chapel Hill.

//While visualizations help us visually interpret satellite imagery, we often need
//quantitative measurements to analyze the landscape.

//Spectral indices allow us to mathematically combine different spectral bands
//to highlight specific land surface characteristics, such as vegetation,
//water, or burned areas.

//Remember our vegetation visualization
var image = ee.Image('COPERNICUS/S2_SR_HARMONIZED/20260313T160041_20260313T160757_T17SPV')

Map.addLayer(
    image, 
    {
        bands: ['B8', 'B4', 'B3'], 
        min: 160,
        max: 2500
    },
    'Vegetation' 
);

//In this false-color composite, healthy vegetation appears dark red because the
//near-infrared (NIR) band is displayed in the red channel. Since healthy vegetation
//reflects a large amount of NIR light, it stands out as shades of red.

//But what if we wanted to represent vegetation health mathematically? 
//We can use GEEs band math, where we combine multiple spectral bands using mathematical formulas

//One of the most widely used spectral indices is the Normalized Difference
//Vegetation Index (NDVI). NDVI compares the near-infrared (NIR) and red bands
//to estimate the presence and health of vegetation.

//Get bands
var nir = image.select('B8');
var red = image.select('B4');

//Calculate the numerator and the denominator using band subtraction and addition
var numerator = nir.subtract(red);
var denominator = nir.add(red);

//calculate NDVI.
var ndvi = numerator.divide(denominator);

//Add the layer
Map.addLayer(ndvi, {
    min: -1,
    max: 1,
    palette: ['red', 'white', 'green']
}, 'NDVI Manual');


//What NDVI values represent high vegetation? Which values represent low vegetation?

//Normalized differences like NDVI are so common in remote sensing that Earth Engine 
//provides the ability to do that particular sequence of subtraction, addition, and division 
//in a single step, using the normalizedDifference method.

//Now use the built-in normalizedDifference function to achieve the same outcome.
var ndviND = image.normalizedDifference(['B8', 'B4']);
Map.addLayer(ndviND, {
    min: -1,
    max: 1,
    palette: ['red', 'white', 'green']
}, 'NDVI normalizedDiff');

//NDVI gives us a continuous value of vegetation
//let's say that we want to categorize our data into highly vegetated and not highly vegetated
//to do this, we can use a threshold

//for instance, let's say that over .7 is highly vegetated. 

// Implement a threshold
//this will set anything above .7 as 1 and anything below as 0
var chVeg = ndviND.gt(0.7);

Map.addLayer(chVeg,
    {
        min: 0,
        max: 1,
        palette: ['white', 'green']
    },
    'Highly Vegetated');
    

// While binary classification is useful, we often want to classify an image
//into more than two categories. For example, we might want to identify
// areas with low, moderate, and high vegetation.

//We can do this using the .where() method which changes the value of pixels that
//satisfy a condition. By applying multiple .where() statements, we can
//build a classified image with several categories.

//Create a starting image where every pixel has a value of 1.
//This will represent areas with moderate vegetation.
var ndviClasses = ee.Image(1)
    .clip(ndviND.geometry());

//Assign pixels with NDVI values less than or equal to 0.3 to class 0.
ndviClasses = ndviClasses.where(ndviND.lte(0.3), 0);

//Assign pixels with NDVI values greater than or equal to 0.7 to class 2.
ndviClasses = ndviClasses.where(ndviND.gte(0.7), 2);

//Pixels with NDVI values between 0.3 and 0.7 remain class 1.

// Display the classified NDVI image.
Map.addLayer(ndviClasses,
    {
        min: 0,
        max: 2,
        palette: ['brown', 'yellow', 'green']
    },
    'Low, Moderate, High NDVI');


//Now suppose we only want to keep the highly vegetated areas.
//updateMask() uses another image (called a mask) to decide which pixels
//should remain visible.
//
// The mask (chVeg) contains:
//   1 = keep this pixel
//   0 = hide this pixel
//
// Since chVeg was created with ndviND.gt(0.7), only pixels with
// NDVI values greater than 0.7 have a value of 1.
//
// Applying updateMask(chVeg) keeps those pixels and hides all others.
// The NDVI values themselves do NOT change, only which pixels are displayed
// and included in later analyses.

var masked = ndviND.updateMask(chVeg);

Map.addLayer(masked,
  {
    min: 0,
    max: 1,
    palette: ['white', 'green']
  },
  'NDVI > 0.7');


//Another common spectral indice is the Normalized Difference Built-Up Index (NDBI)
//For Sentinel-2, it is the normalized difference between band 11 (SWIR) and band 8 (NIR)

//Calculate NDBI using the normalizedDifference() method. 
//Display the NDBI image using an appropriate color palette.
//Create a threshold that identifies pixels with NDBI values greater than 0.
//Display your thresholded image.

// Where are the highest NDBI values located?
//How do these locations compare to the highly vegetated areas identified with NDVI?


// Create a three-class NDBI image using .where().
//
// Assign: 0 = NDBI <= 0, 1 = 0 < NDBI < 0.2, 2 = NDBI >= 0.2
//
// Experiment with different thresholds and compare the results
```

## Tutorial 11: Feature Collections, Clip, and Export

Download the data for the tutorial [here](https://drive.google.com/file/d/1JN321-l0iWzYpJTlEVPRiqwCMus-bi7Z/view?usp=sharing)

After completing this tutorial you should be able to:

- Create and visualize features and feature collections
- Import vector datasets as assets
- Clip images to a reguion of interest using vector data
- Export images from Google Earth Engine to Google Drive

``` javascript
//So far, we've only worked extensively with Images and Image Collections.

//At times, however, we have created geometries (for instance, for filtering),
//using the ee.Geometry.Point() function. This point, which we can also
//add to a map
var point = ee.Geometry.Point(-79.0873, 35.9147);

//uncomment the command below
//Map.addLayer(point);

//A single point, polygon, or line is called a feature. 
// Multiple features are called a feature collection
var points = [
  ee.Geometry.Point(-79.0873, 35.9147),
  ee.Geometry.Point(-78.7873, 35.8147),
  ee.Geometry.Point(-78.5873, 35.7147)
];

var point_collection = ee.FeatureCollection(points);


//uncomment the command below
//Map.addLayer(point_collection)


// You can also make features and feature collections using the geometry 
// buttons below (look above the zoom in / zoom out buttons on the map)

//Try to make a new feature using those geometry buttons


//Try to make a new feature collection using the geometry buttons



//Finally, you can import features or feature collections.


//Click on Assets and find the "New" button. 
//Upload the "North_Carolina_Counties.geojson" from the course website


//Once it has fully uploaded click the "->" button next to the asset
//to read it into the script. 


//You can use features and feature collections for a variety of tasks. An
//important one is clipping images/image collections to a region of interest


//Clip the following image to North Carolina using the following syntax
//and add it to the map
var drought = ee.ImageCollection("GRIDMET/DROUGHT").first()

//var clipped = image.clip(geometry)





// Awesome! Another important task might be exporting an image so that
// you can use it in another software like QGIS
//You export images directly to your Google Drive using the following syntax


// Export.image.toDrive({
//   image: IMAGE, //this is the image you want to export
//   description: "NAME" ,//this is what you want to name the file
//   scale: NUMBER, // Scale. Find this from the catalog entry as pixel size
//   fileFormat: 'GeoTIFF' // Specify the file format
// });


//Export your clipped image to your google drive
```

## Tutorial 12: Mapping Over Image Collections

After completing this tutorial you should be able to:

- Write a function that performs an operation on an image
- Map a function across every image in an image collection
- Add a calculated band to each image in a collection

``` javascript

//In Tutorial 7, we used .map() to apply a cloud masking function to every image 
//in a Landsat image collection. The same approach can be used for many other tasks, 
//such as unit conversions, calculating spectral indices,or adding new bands to every image.


//"Mapping" over an image collection involves applying the same operation 
//over the entire image collection. 


//For instance, let's say we want to look at rainfall during Hurricane Florence
//using the RTMA dataset. 


//The precipitation variable in the RTMA dataset is in kg/m^2
//which is not an easily interpretable value. 

//We might want to add a new band called "precip_inches" to every
//image in an image collection that has been filtered to North Carolina
//during the dates of hurricane florence.

//We would do that by running the following 


// // Define the region of interest (ROI) - North Carolina
// var roi = ee.Geometry.Rectangle([-84.3219, 33.7529, -75.4606, 36.5880]);

// // Load the RTMA ImageCollection for a period around Hurricane Florence
// var rtmaCollection = ee.ImageCollection('NOAA/NWS/RTMA')
//   .filterDate('2018-09-10', '2018-09-20')
//   .select('ACPC01');

// // Function to convert precipitation from kg/m² to inches
// var kgm2ToInches = function(image) {
//   var precipitation = image.select('ACPC01');
//   var precipitationInches = precipitation.multiply(0.0393701).rename('precip_inches');
//   return image.addBands(precipitationInches);
// };

// // Map the conversion function over the RTMA collection
// var precipitationInchesCollection = rtmaCollection.map(kgm2ToInches);


//Print the image collection. If you look at the bands in any of the images
//there should be a new band called 'precip_inches'

//Clip the image collection to the area of interest


//Write a script that creates a composite of the 'precip_inches' band 
// of that image collection using the .sum() command. 
//hint: you also need to use .select('precip_inches') before you use the 
//sum command to only sum the precip_inches band


//Add the composite to the map with appropriate visualization parameters


//Which areas of North Carolina recieved the most rainfall during Florence?

//Filter RTMA to dates for Hurricane Helene in WNC. 

//Visit the data catalog entry for RTMA. Identify the wind gust band and write a function that
//converts gusts from m/s to mph. Map that across the filtered image 

//Use a composite with the .max() function to visualize maximum wind gust
```

## Tutorial 13: Reducers

After completing this tutorial you should be able to:

- Explain how reducers summarize image collections and raster values
- Use reduceRegions() to calculate statistics for features and feature collections
- Export summary statistics as a .csv

``` javascript
//We have already used reducers when creating composites
//Reducers can be used to reduce all the images in an image collection
//the most common reducers include .mean(), .sum(), .median()

//What these reducers do is reduce an Image Collection to a single Image. 


//However, you can also use reducers to reduce Images or Image Collections across
//Features or Feature Collections

//For this, we will use the .reduceRegions() function. 


//First, add your North Carolina county asset to this script. 

//Now uncomment the command below to load a DEM image
//var dem = ee.Image('CGIAR/SRTM90_V4');

//To reduce this image across North Carolina counties, we will use the
//following syntax

//var projection = dem.projection();

//the scale should be the pixel resolution of the dataset
// var nc_county_elevation = dem.reduceRegions({
//   collection: table,
//   reducer: ee.Reducer.mean(),
//   scale: projection.nominalScale(),
//   crs: projection
// });



//write a command to print the output of this reduction


//To export this file to your drive, you would use the following syntax
// Export.table.toDrive({
//   collection: nc_county_elevation,
//   description: 'NC_County_Elevation',
//   fileFormat: 'CSV'
// });



//What about if you want to use .reduceRegions with an image collection?
//What I usually do is first create a composite of an image collection and then
//use the reduceRegions() function. 

//Let's practice on the following dataset
//https://developers.google.com/earth-engine/datasets/catalog/ECMWF_ERA5_LAND_MONTHLY_AGGR


//First, create an image collection that includes all images from 2023 and 
//selects just the 'total_precipitation_sum' band.


//Now create a composite image. You can decide if you want to calculate
//the mean or the median 


//add this image to the map using appropriate visualization parameters



//Now reduce that image to the North Carolina counties and export your
//results. Notice that this requires you to use another reducer. 

//This reducer can be the same one you used to create the composite
//or it can be a different one. For instance, you can composite the 
//mean but decide to take the max when reducing to regions.
//What that returns is the max average value in each region. 

```
